(define (domain logistics)
  (:requirements :strips)
  (:predicates
    (airplane ?a)
    (airport ?ap)
    (truck ?t)
    (location ?l)
    (city ?c)
    (package ?p)
    (in ?p ?t)
    (at ?p ?l)
    (at ?t ?l)
    (at ?a ?ap)
  )
  (:action load-truck
    :parameters (?p ?t ?l)
    :precondition (and (package ?p) (truck ?t) (location ?l) (at ?p ?l) (at ?t ?l))
    :effect (and (in ?p ?t) (not (at ?p ?l)))
  )
  (:action unload-truck
    :parameters (?p ?t ?l)
    :precondition (and (package ?p) (truck ?t) (location ?l) (in ?p ?t) (at ?t ?l))
    :effect (and (at ?p ?l) (not (in ?p ?t)))
  )
  (:action drive-truck
    :parameters (?t ?from ?to ?c)
    :precondition (and (truck ?t) (location ?from) (location ?to) (city ?c) (at ?t ?from))
    :effect (and (at ?t ?to) (not (at ?t ?from)))
  )
  (:action load-airplane
    :parameters (?p ?a ?ap)
    :precondition (and (package ?p) (airplane ?a) (airport ?ap) (at ?p ?ap) (at ?a ?ap))
    :effect (and (in ?p ?a) (not (at ?p ?ap)))
  )
  (:action unload-airplane
    :parameters (?p ?a ?ap)
    :precondition (and (package ?p) (airplane ?a) (airport ?ap) (in ?p ?a) (at ?a ?ap))
    :effect (and (at ?p ?ap) (not (in ?p ?a)))
  )
  (:action fly-airplane
    :parameters (?a ?from ?to)
    :precondition (and (airplane ?a) (airport ?from) (airport ?to) (at ?a ?from))
    :effect (and (at ?a ?to) (not (at ?a ?from)))
  )
)
